v1.1.3
commit 8c991d1ec620a1797bb96cc29c9a7bb98ec7206b
Author: q-1-p <github.pubilc@outlook.com>
Date:   Wed Jul 2 06:06:54 2025 +0900

    feat: Add google analytics

commit a9e328ee705537507abc0eb1279c1cba3e25738d
Author: q-1-p <github.pubilc@outlook.com>
Date:   Wed Jul 2 06:06:23 2025 +0900

    feat: Resend when mail fails to send

commit 638f691015b3d18b544153571ff2f2ce939acbb4
Author: q-1-p <github.pubilc@outlook.com>
Date:   Sun Jun 29 21:08:25 2025 +0900

    fix: Correct error

    Run git checkout production
    Switched to a new branch 'production'
    branch 'production' set up to track 'origin/production'.
    Committer identity unknown

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

    to set your account's default identity.
    Omit --global to set the identity only in this repository.

    fatal: empty ident name (for <runner@pkrvmbietmlfzoi.motzxs420emefmycxb4gafpwpg.bx.internal.cloudapp.net>) not allowed
    Error: Process completed with exit code 128.

commit 35cd663eb52a59c3f8865f801aae8e96eae9e81d
Author: q-1-p <github.pubilc@outlook.com>
Date:   Sun Jun 29 21:03:36 2025 +0900

    chore: Modify name of representative

commit 6704d0f19844d11f93db7951db0cfa0025b3110f
Author: q-1-p <github.pubilc@outlook.com>
Date:   Mon Jun 23 21:14:50 2025 +0900

    chore: Add crawler support

commit 1835a7d9f838a6d90c03630cdbfc7fd99abc79ed
Author: q-1-p <github.pubilc@outlook.com>
Date:   Mon Jun 23 07:06:45 2025 +0900

    chore: Add auto merge workflow

commit fca6a85fbabb6d52133d8aa8d3abc029e74560b1
Author: q-1-p <github.pubilc@outlook.com>
Date:   Sun Jun 22 19:04:27 2025 +0900

    fix: Revise the formula for future payment amounts.

    Because they did not take into account periods of non-renewal, etc.