fix: Correct error
Run git checkout production
Switched to a new branch 'production'
branch 'production' set up to track 'origin/production'.
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@pkrvmbietmlfzoi.motzxs420emefmycxb4gafpwpg.bx.internal.cloudapp.net>) not allowed
Error: Process completed with exit code 128.